name: Tests
on: [push, pull_request]

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse # Should improve the speed of the build and the cache size.
  ZSTD_CLEVEL: 10 # We want some tradeoff between speed and size.
  ZSTD_NBTHREADS: 2 # We only got 2 cores.

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc

      - name: Run cargo check
        run: cargo check --tests

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc

      - name: Run cargo test regular features
        run: cargo test

      - name: Run cargo test no asm
        run: cargo test --features=no-asm

      - name: Run cargo test with parking_lot
        run: cargo test --features=parking_lot

      - name: Run cargo test shuttle
        run: cargo test --features=shuttle

  test-release:
    name: Test Suite Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc

      - name: Run cargo test release regular features
        run: cargo test --release

      - name: Run cargo test release no asm
        run: cargo test --features=no-asm --release

      - name: Run cargo test release with parking_lot
        run: cargo test --features=parking_lot --release

      - name: Run cargo test release shuttle
        run: cargo test --no-default-features --features=shuttle --release

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --tests -- -D warnings
